# Generated by Django 2.1.5 on 2019-03-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='category',
        ),
    ]
