# Generated by Django 2.1.5 on 2019-03-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20190308_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='area',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='garage',
            field=models.CharField(max_length=20),
        ),
    ]
